.test config:
  stage: test
  image: debian:bookworm-slim

  before_script:
  - >
    if [[ $CI_DISPOSABLE_ENVIRONMENT ]]; then
      apt-get update -qy
      apt-get install -qy --no-install-recommends ca-certificates curl git jq binutils xz-utils
    fi
  - mv _output _input
    
  script:
  - ./test-config "${LINUX_FLAVOUR}" "${JOB_HOST_ARCH}"

test config amd64:
  extends: .test config
  variables:
    JOB_HOST_ARCH: amd64
    LINUX_FLAVOUR: amd64
  dependencies:
  - build all
  - build amd64
  rules:
  - if: '$BUILD_ARCH_AMD64 != ""'


test config amd64 cloud:
  extends: .test config
  variables:
    JOB_HOST_ARCH: amd64
    LINUX_FLAVOUR: "cloud-amd64"
  dependencies:
  - build all
  - build amd64
  rules:
  - if: '$BUILD_ARCH_AMD64 != ""'

test config arm64:
  extends: .test config
  variables:
    JOB_HOST_ARCH: arm64
    LINUX_FLAVOUR: arm64
  dependencies:
  - build all
  - build arm64
  rules:
  - if: '$BUILD_ARCH_ARM64 != ""'

test config arm64 cloud:
  extends: .test config
  variables:
    JOB_HOST_ARCH: arm64
    LINUX_FLAVOUR: "cloud-arm64"
  dependencies:
  - build all
  - build arm64
  rules:
  - if: '$BUILD_ARCH_ARM64 != ""'
